#!/usr/bin/env bash
#
# Author: Alalilacias
# Description: Creates custom aliases in .zshrc when invoked.
# Syntax: source aliases
# Version: 0.1
# Ref: https://github.com/Phantas0s/.dotfiles/blob/master/aliases/aliases && https://thevaluable.dev/zsh-install-configure-mouseless/
# Manpages ref: https://man7.org/linux/man-pages/index.html

# Apt
alias apti='sudo apt install'
alias aptu='sudo apt update'
alias aptU='sudo apt upgrade'
alias aptuu='sudo apt update && sudo apt upgrade'
# Don't judge me for not being a coward. I saw the opportunity and I took it.
# Would normally be apturu following my previous logic, but I was listening to
# Synthwave as I set this up, and the song screamed it, so i felt obligated.
# Ended up upgrading it, so now aptuwu is more than ever before.
alias aptuwu='sudo apt update && sudo apt upgrade && sudo apt autoremove && flatpak update && flatpak uninstall --unused && flatpak repair'

# Copy
alias cp='cp -iv'

# Dotfiles, and important locations
alias dotfiles='cdl ~/.dotfiles'
alias dotconfig='cdl ~/.dotfiles/.config'
alias dotbin='cdl ~/.dotfiles/bin'
# Felt cute, might delete later. Ja, I have found changing to this directory too often these days. Might delete when it's less necessary.
alias zshfiles='cdl ~/.dotfiles/.config/zsh'

# Git
alias ga='git add'
alias gaa='git add .'
alias gaf='git add -f'
alias gb='git branch'
alias gbr='git branch -r'
alias gc='git commit'
alias gco='git checkout'
alias gp='git push'
alias gplo='git pull origin'
alias gpo='git push origin'
alias gr='git remote'
alias gro='git remote origin'
alias grs='git remote show'
alias gs='git status'
alias gsi='git status --ignored'

# List
alias ll='ls -laAhF --group-directories-first'
alias lls='ls -lahFtr'

# Move/Rename
alias mv='mv -iv'

# Make Directory
alias mkdir='mkdir -pv'

# Nvim
alias vim='nvim'
alias vi='nvim'

# Remove
alias rm='rm -iv'

# Studies
# These are to be constantly adapted to the current needs

alias studies='cdl ~/Documents/Studies && ll'
alias law='cdl ~/Documents/Studies/Law && ll'
alias lawc='cdl ~/Documents/Studies/Law/2024-2025/semester_two'
alias ciaa='cdl ~/Documents/Studies/Law/2024-2025/semester_two/ciaa'
alias ciaac='cdl ~/Documents/Studies/Law/2024-2025/semester_two/ciaa/classes'
alias clapl='cdl ~/Documents/Studies/Law/2024-2025/semester_two/clapl'
alias claplc='cdl ~/Documents/Studies/Law/2024-2025/semester_two/clapl/classes'
alias dfis='cdl ~/Documents/Studies/Law/2024-2025/semester_two/dfis'
alias dfisfc='cdl ~/Documents/Studies/Law/2024-2025/semester_two/dfis/familia/classes'
alias dfissc='cdl ~/Documents/Studies/Law/2024-2025/semester_two/dfis/sucessions/classes'
alias die='cdl ~/Documents/Studies/Law/2024-2025/semester_two/die'
alias diec='cdl ~/Documents/Studies/Law/2024-2025/semester_two/die/classes'
alias dpi='cdl ~/Documents/Studies/Law/2024-2025/semester_two/dpi'
alias dpic='cdl ~/Documents/Studies/Law/2024-2025/semester_two/dpi/classes'
alias itf='cdl ~/Documents/Studies/Law/2024-2025/semester_two/itf'
alias itfc='cdl ~/Documents/Studies/Law/2024-2025/semester_two/itf/classes'

# XDG-related (I am currently still fairly ignorant on what XDG is. Until I learn enough to feel confident, it'll remain "-related" to avoid possible confusions)
alias open='xdg-open'
alias oc='xdg-open .'

# Zsh
# If anyone wants to suggest a better abbreviation, I'll appreciate it a lot.
alias nalias='nvim ~/.dotfiles/.config/zsh/aliases'
