#!/usr/bin/env bash
#
# Author: Alalilacias
# Description: Creates custom functions in .zshrc when invoked.
# Syntax: source pfunctions
# Version: 0.3

# Makes all cd calls use the ll alias to lists files below the directory we moved to the way I like it.
cdl() {
  cd "$@" && ll
}

# Allows to create a directory and change to it. Have never used it.
mkcd() {
  mkdir -p "$1" && cdl "$1"
}

check_git() {
  local SEARCH_DIR=~
  echo "Scanning for git repos in $SEARCH_DIR..."

  find "$SEARCH_DIR" \( \
    -path "$HOME/.local" -o \
    -path "$HOME/.cache" -o \
    -path "$HOME/.cargo" -o \
    -path "$HOME/.nvm" -o \
    -path "$HOME/.config/nvm" -o \
    -path "$HOME/.Trash" -o \
    -path "/timeshift" \
    \) -prune -false -o -type d -name ".git" 2>/dev/null | while read -r gitdir; do
    repo_dir="$(dirname "$gitdir")"
    if git -C "$repo_dir" rev-parse --is-inside-work-tree &>/dev/null; then
      git_status=$(git -C "$repo_dir" status --porcelain --untracked-files=no)
      ahead=$(git -C "$repo_dir" rev-list @{u}..HEAD 2>/dev/null | wc -l | tr -d ' ')

      if [[ -n "$git_status" || "$ahead" -ne 0 ]]; then
        echo "→ $repo_dir"
        [[ -n "$git_status" ]] && echo "$git_status" | sed 's/^/   /'
        [[ "$ahead" -ne 0 ]] && echo "   Unpushed commits: $ahead"
      fi
    fi
  done
}

# Measure the startup time of the shell (default: $SHELL) by running it 10 times.
# Uses '/usr/bin/time' to track execution time.
# The shell starts in interactive mode (-i) but only executes 'exit' (-c exit).
timezsh() {
  local shell=${1:-$SHELL}                    # Use the provided shell or default to $SHELL
  repeat 10 /usr/bin/time "$shell" -i -c exit # Run the timing test 10 times
}
