#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Composer (PHP dependency manager)
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/composer"
# Version: 0.7

log_debug "Checking for php..."
if ! command -v php &>/dev/null; then
  log_error "php not found. Cannot install Composer."
  return 1
fi

log_debug "Installing Composer..."

BIN_DIR="$HOME/.local/bin"
TMP_DIR="$(mktemp -d -t composer-install-XXXXXX)"

mkdir -p "$BIN_DIR"

trap 'rm -rf "$TMP_DIR"' RETURN

log_debug "Downloading Composer installer..."
curl -sS https://getcomposer.org/installer -o "$TMP_DIR/composer-setup.php"

log_debug "Verifying installer checksum..."
EXPECTED_CHECKSUM=$(curl -sS https://composer.github.io/installer.sig)
ACTUAL_CHECKSUM=$(php -r "echo hash_file('sha384', '$TMP_DIR/composer-setup.php');")

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
  log_error "Invalid Composer installer checksum."
  return 1
fi

log_debug "Running installer..."
php "$TMP_DIR/composer-setup.php" --install-dir="$TMP_DIR" --filename=composer.phar

log_debug "Moving binary to $BIN_DIR/composer"
mv "$TMP_DIR/composer.phar" "$BIN_DIR/composer"
chmod +x "$BIN_DIR/composer"

log_info "Composer installed successfully to $BIN_DIR/composer"
return 0
