#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Go into ~/.local/go
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/go"
# Version: 0.4

GO_VERSION="1.22.0"
GO_DIR="$HOME/.local/go"
TMP_DIR="/tmp/dotfiles-go-install"

log_info "Installing Go $GO_VERSION..."

mkdir -p "$TMP_DIR" "$GO_DIR"
cd "$TMP_DIR" || exit 1

curl -LO "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
tar -C "$GO_DIR" --strip-components=1 -xzf "go${GO_VERSION}.linux-amd64.tar.gz"

rm -rf "$TMP_DIR"
log_info "Go $GO_VERSION installed to $GO_DIR"
