#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs tree-sitter CLI via npm
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/tree-sitter"
# Version: 0.6

if ! command -v npm &>/dev/null; then
  log_error "npm is not installed or not on path. Cannot install tree-sitter"
  return 1
fi

npm install -g tree-sitter-cli

log_info "tree-sitter installed successfully."
