#!/usr/bin/env bash
#
# Author: Alalilacias
# Description: Creates custom aliases in .zshrc when invoked.
# Syntax: source aliases
# Version: 0.1
# Ref: https://github.com/Phantas0s/.dotfiles/blob/master/aliases/aliases && https://thevaluable.dev/zsh-install-configure-mouseless/
# Manpages ref: https://man7.org/linux/man-pages/index.html

# Apt
alias apti='sudo apt install'
alias aptu='sudo apt update'
alias aptU='sudo apt upgrade'
alias aptuu='sudo apt update && sudo apt upgrade'
# Don't judge me for not being a coward. I saw the opportunity and I took it.
# Would normally be apturu following my previous logic, but I was listening to
# Synthwave as I set this up, and the song screamed it, so i felt obligated.
# Ended up upgrading it, so now aptuwu is more than ever before.
alias aptuwu='sudo apt update && sudo apt upgrade && sudo apt autoremove && flatpak update && flatpak uninstall --unused && flatpak repair'

# Copy
alias cp='cp -iv'

# Dotfiles, and important locations
alias dotfiles='cdl ~/.dotfiles'
alias dotconfig='cdl ~/.dotfiles/.config'
alias dotconfiles='cdl ~/.dotfiles/.config/dotfiles'
alias dotcoconfig='cdl ~/.dotfiles/.config/dotfiles/config/'
alias dotcoscripts='cdl ~/.dotfiles/.config/dotfiles/scripts/'
alias dotbin='cdl ~/.dotfiles/bin'
# Felt cute, might delete later. Ja, I have found changing to this directory too often these days. Might delete when it's less necessary.
alias zshfiles='cdl ~/.dotfiles/.config/zsh'

# Environmentally dependant aliases
if [ -f "$HOME/.dotfiles/.config/zsh/modules/environment/aliases.env" ]; then
  source "$HOME/.dotfiles/.config/zsh/modules/environment/aliases.env"
else
  echo "Unable to locate environment aliases"
fi
alias nealias='nvim ~/.dotfiles/.config/zsh/modules/environment/aliases.env'

# Functions
alias nfunctions='nvim ~/.dotfiles/.config/zsh/modules/functions/functions'

# Environmentally dependant aliases
if [ -f "$HOME/.dotfiles/.config/zsh/modules/environment/functions.env" ]; then
  source "$HOME/.dotfiles/.config/zsh/modules/environment/functions.env"
else
  echo "Unable to locate environment aliases"
fi
alias nefunctions='nvim ~/.dotfiles/.config/zsh/modules/environment/functions.env'

# Git
alias ga='git add'
alias gaa='git add .'
alias gac='gaa && gc'
alias gacpo='gaa && gc && gpo'
alias gaf='git add -f'
alias gb='git branch'
alias gbd='git branch -d'
alias gbr='git branch -r'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gm='git merge'
alias gp='git push'
alias gplo='git pull origin'
alias gpo='git push origin'
alias gpod='git push origin --delete'
alias gposu='git push --set-upstream origin'
alias gr='git remote'
alias gro='git remote origin'
alias grs='git remote show'
alias gs='git status'
alias gsi='git status --ignored'
alias gsw='git switch -c'

# Lazy
alias lazy='cdl ~/.dotfiles/.config/nvim'
alias lazyconfig='cdl ~/.dotfiles/.config/nvim/lua/config'
alias lazyplugins='cdl  ~/.dotfiles/.config/nvim/lua/plugins'
alias lazypcommands='cdl ~/.dotfiles/.config/nvim/lua/config/commands'
alias lazycommands='lazyconfig && nvim autocmds.lua'
alias lazykeymaps='lazyconfig && nvim keymaps.lua'
alias lazyoptions='lazyconfig && nvim options.lua'

# List
alias lls='ls -lahFtr'
alias llt='tree -CahF --dirsfirst'

# Move/Rename
alias mv='mv -iv'

# Make Directory
alias mkdir='mkdir -pv'

# Nvim
alias vim='nvim'
alias vi='nvim'

# Remove
alias rm='rm -iv'

# Refresh
alias refresh_console='source ~/.zshrc'

# Secret aliases
if [ -f "$HOME/.dotfiles/.config/zsh/modules/secrets/aliases.secrets" ]; then
  source "$HOME/.dotfiles/.config/zsh/modules/secrets/aliases.secrets"
else
  echo "Unable to locate secret aliases"
fi
alias nsalias='nvim ~/.dotfiles/.config/zsh/modules/secrets/aliases.secrets'

# XDG-related (I am currently still fairly ignorant on what XDG is. Until I learn enough to feel confident, it'll remain "-related" to avoid possible confusions)
alias open='xdg-open'
alias oc='xdg-open .'

# Zsh
# If anyone wants to suggest a better abbreviation, I'll appreciate it a lot.
alias nalias='nvim ~/.dotfiles/.config/zsh/modules/aliases/aliases'
